name: Run Spider Script

on:
  schedule:
    - cron: "0 */4 * * *" # Runs every 4 hours

jobs:
  run-spider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run spider script
        run: |
          python spider/spider.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: spider-results
          path: data_*.json
          compression-level: 9